### PR TITLE
Client capi ds4

### PR DESCRIPTION
**Pull request by HipsterSloth**
@cboulay No rush on this (it's not blocking me). I just wanted to leave this here until you have time to look it over.

I have the DS4 changes from master merged with the CAPI changes in client_capi_ds4 (branched off client_capi).  This was mostly an addition of new code rather than a changing existing code. 

The one exception is with the RawSensorData structure. That structure was confusing because the accelerometer and gyro readings were actually calibrated values while the magnetometer was the raw sensor bytes. There are now a RawSensorData and CalibratedSensorData structs. The raw struct contains the raw sensor bytes (ints), while the calibrated struct has the raw sensor values with gains/biases applied (floats). 

I updated `test_console_CAPI` and `test_psmoveclient.py` to use the new calibrated sensor data struct. The accelerometer and gyro values are the same as before, but the magnetometer is now a normalized magnetometer direction. This might be why you were having trouble with the ported orientation filter you were trying to get working.

Also since I was using a 64-bit build of the PSMoveService I installed the "Windows x86-64 MSI installer" from https://www.python.org/downloads/release/python-2712/ and then did the following in the console.

```
>python.exe -m pip install -U pip
>python.exe -m pip install cffi
>SET VS90COMNTOOLS=%VS140COMNTOOLS%
>python.exe compile_psm.py
>python.exe test_psmoveclient.py
```

As was mentioned in the other PR, all the DS4 work is described in the following two videos. I made them in part because this is an unreasonable amount of code to review so the videos help give some context and hopefully assuage any fears about the PR.

Part1 - (8min) https://youtu.be/ywxjFAQuxkQ
Part2 - (13min) https://youtu.be/MPbegaB7cf0

I leave this PR sitting until you are ready for it to be added to the client_capi branch. In the mean time I'm going to start working on the C++ UKF in a new branch off of master.

### CODE REVIEW

**Comment by cboulay** [comment]
OK. I finally finished some of my non-mainline work that has been taking up my evenings so I can look at this tonight. By the way, if you're new to Python, go straight to 3.5. It has a few advantages, but one subtle one that applies in this case is its development libraries are built with MSVC2015 so there shouldn't be any need to `SET VS90COMNTOOLS=%VS140COMNTOOLS%`.

**Comment by HipsterSloth** [comment]
Ah! Good to know about python 3.5 (it's been a long time since I've used it regularly). I will install that now.

**Comment by cboulay** [comment]
So are the gyro and accel calibration actually being used for the PSMove? I thought they were unnecessary for the PSMove because of the calibration packet. Also, according to your video, these things are unnecessary for the DS4 because you just need constants?
Or is there more happening here? (i.e. calculating drift, covariance, etc.)

Testing accelerometer calibration didn't seem to work (0.0 printed on screen, no response to movements).

**Comment by HipsterSloth** [comment]
Oh sorry that wasn't very clear from the video. Yeah the accel and gyro calibration originally served two purposes: 

1) A testbed for compute the sensor scales for the DS4
2) Compute noise statistics for the PSMove and DS4

Use case 1 went away so now both are just used to compute the "Variance" and "Drift" config values from the gyro and the "NoiseRadius" value for the accelerometer.

The accelerometer calibration test at the end is a bit confusing too. After the config is done, it shows linear_acceleration, not the accelerometer value. The linear acceleration is currently zero'd out for the PSMove because it was too noisy (waiting for the low pass filter). With the DS4 it will show a linear acceleration (because that has a different filter). I should probably render both the accelerometer and the linear acceleration.

**Comment by cboulay** [comment]
eh, don't do it on my account. This isn't going into main yet. I just wanted to make sure it was expected behaviour and not something else (e.g., Mac specific).

BTW, when merging and moving stuff around, I foolishly discarded my work on implementing your complementary filter in Python to use as a baseline for orientation estimation. I had copied it to a separate folder to keep it safe when I merged, and upon realizing your work didn't touch those files I deleted the copied folder, but I had forgotten that I did a `git checkout .` before that and didn't previously commit these changes. Stupid me.

It's not that big of a deal, especially because I can just read the estimated orientation directly from PSMoveService anyway. I just wanted to make sure I understood what was going on. I'll come back it if I get stuck on the UKF work.

**Comment by HipsterSloth** [comment]
I've done that before when cleaning old branches myself. That's the worst feeling. Glad it wasn't anything critical at least.

By the way I'm currently in the middle of cleaning up the position/orientation filter framework in psmoveservice to accommodate the notion of a "PoseFilter". Currently we filter orientation and position separately, but they are filtered together with the new Kalman filter. To make this work there is a new IPoseFilter interface that the Kalman filter and the "CompoundPose" filter implement. The new compound pose filter just wraps up the old orientation and position filters (cleaned up a bit). The ServerControllerView will have a IPoseFilter pointer instead of OrientationFilter and PositionFilter pointer like it does now. I should have that done by EOD. I post a link to the check-in here so you can review it and give any feedback you might have about the changes.

**Comment by HipsterSloth** [comment]
I just checked in the orientation/position filter refactor: https://github.com/cboulay/PSMoveService/commit/f9a9ecf841030c1c199eeac191217affff49922b

It compiles, but it's totally untested. I'll continue to work on this as I have time this weekend. Let me know if there is anything you want tweaked or added.

**Pull request merged**
