### PR TITLE
Virtual hmd

### PR DESCRIPTION
**Pull request by HipsterSloth**
Adding support for VirtualHMDs to PSMoveService (tracking an LED illuminated ping pong ball attached to an HMD that doesn't have positional tracking). The tracking works basically the same as tracking a psmove controller minus any sensor data (the orientation is always the identity quaternion). To add a new virtual hmd edit `%appdata%/PSMoveService/HMDManagerConfig.json` and set "virtual_hmd_count" to "1". When PSMoveService.exe is launched it will create the config file `%appdata%/PSMoveService/VirtualHMD__0.json`. Make sure the "bulb radius" parameter matches the radius of your tracking bulb (2cm for a regulation ping pong ball). The tracking color can be set in the HMD Settings panel of psmoveconfig.

### CODE REVIEW

**Comment by HipsterSloth** [comment]
@zelmon64 if you have a some time I'd love if you could give this PS a look over. It's very similar in spirit to the virtualHMD change you were working on. 

I decided to do with a single "VirtualHMD" device instead of a SingleBulbHMD and MultiBulbHMD device like you had in your branch. My thought was that the same virtual hmd could handle different bulb setups based on configuration. The IHMDInterface has a getTrackingShape() method on it that can just return a different tracking shape in the case of multibulb. Then it's up to the tracker code to try and compute the pose from the HMD tracking shape.

I tried to preserve the spirit of the buttons in PSMoveConfig for changing between testing tracking, color configuration, and video feed testing with a single device or all devices. When you select "All" you get all controllers and all HMDs since they share the same pool of 6 available tracking colors.

**Comment by zelmon64** [comment]
@HipsterSloth no problem. This is really awesome work! Your single "VirtualHMD" device makes sense. I tried it out in PSMoveConfigTool and was really impressed! The only odd thing was that the debug overlay info is showing when calibrating the colour for the VirtualHMD.

It actually took me a while to build the project because I accidentally wiped my C drive a week ago. What was causing a problem turned out to be MSBuild.exe. I didn't realise I had to manually add it's path to environment variables. Should that be added to the build instructions or did I just miss something which would have fixed it automatically?

**Comment by cboulay** [comment]
@zelmon64 , about MSBuild...
If you're doing commands manually in a command prompt, usually you'll first open the command prompt with a batch file that sets your paths for you. It is not desirable to set this permanently because different projects will require different versions of MSVC. If you're using InitialSetup_x64.bat, this should be handled for you (see [here](https://github.com/cboulay/PSMoveService/blob/master/InitialSetup_X64.bat#L29)).

If you don't have MSVC14 installed or it is installed in a different folder than the default, then the setup script won't find the batch file that sets your PATH.

**Comment by zelmon64** [comment]
@cboulay Thanks that makes a lot of sense. I removed MSBuild from my environment variables and when I then run vcvarsall.bat it recognises MSBuild.exe. vcvarsall.bat is in the default location.

This is what I get when I run InitialSetup_x64.bat: 
[InitialSetup_X64.txt](https://github.com/cboulay/PSMoveService/files/1038472/InitialSetup_X64.txt)

If I remove the `amd64` from the end of [the line](https://github.com/cboulay/PSMoveService/blob/master/InitialSetup_X64.bat#L29) then it seems to work for me. I don't quite understand this since it used to work fine for me how it was before I had to reinstall the OS and programs.

**Comment by cboulay** [comment]
@zelmon64 , open a fresh command prompt and run the following commands:

```
echo %PATH%
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
echo %PATH%
MSBuild
```

If the second line doesn't work then your MSVC install is broken.
If it works then see how the path changed. Hopefully the correct paths were added and MSBuild worked. Here are the new paths added for me:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;
```

**Comment by zelmon64** [comment]
@cboulay yes that second line doesn't work for me. All I have in the amd64 folder is vcmeta.dll. Should I try reinstalling Visual Studio 2015?

**Comment by cboulay** [comment]
Sounds like a reinstall is needed. I thought it was in there by default, but keep an eye out for an option to install 64-bit support.

**Comment by HipsterSloth** [comment]
@zelmon64 Ah good catch with the debug rendering. Turns out I was enabling the HMD data stream with positional tracking in the color calibration tool. This turns on the debug rendering. I think I originally did this for Morpheus color calibration since enabling positional tracking was the only way to signal turning on the tracking lights. Since I'm not officially supporting Morpheus tracking yet, I won't worry about that for the time being. I also found another bug when switching from hmd color calibration that I just fixed.

**Comment by cboulay** [comment]
FYI I was able to build this in MacOS except I had to repoint libstem_gamepad to the branch with the fix. Apparently that was broken 3 months ago... shows you how busy I've been. bdb9844a4a9bfddbe48d4459047e8f6fc5a8eea7

**Pull request merged**
