### PR TITLE
throwing power adjustment after recent fixes

### PR DESCRIPTION
**Pull request by gb2111**
throwing was really to weak after recent improvements.
i tested most games and doubling the calculation does best work. no need paraemter really.

### CODE REVIEW

**Comment by zelmon64** [comment]
@gb2111 I had a go with this increased throwing power and it's much better than it was but I'm wondering if it's a bit over powered now.

I also noticed that smoothv seems to be unused and so could be removed.

Lastly I was wondering why there are so many commits for this little change?

**Comment by gb2111** [comment]
Hi Zelmod,
I think those are sync back from main. 
Are you saying we should change it or make parameter? Perhaps you can suggest better parameter.
If that is not used then I will remove indeed. Please let us decide on the parameter and then I can cancel this one and resubmit.
Greg

**Comment by zelmon64** [comment]
Oh I think I understand now. You do your changes to your master instead of a branch. I think the normal process is to make a branch from master to make the changes in so that the branch can be rebased off master if there are any updates or to revert things (that's what I've been doing but I could be wrong).

I was wondering about making it an adjustable parameter like the prediction time but wasn't sure if that would make it too complicated. Another consideration would be how the camera frame rates might effect it (I'll test in a mo) so adjustable throwing power might be needed to compensate for it unless we can make it auto-compensate.

**Comment by gb2111** [comment]
Hi William,
Yes, we have position and speed so potentially we could calculate forecast from it. Unfortunately I am not able to spend time right now. That was supposed to be simple solution until kalman is in place. No scence there. So I am bit afraid of going into more complexity.

So far I was doing pull request and HS was merging it.
Are you saying we should make different way now?

**Comment by zelmon64** [comment]
Hi Greg,

Yeah sorry, I think I lost the plot a bit about the simple nature of this solution. You're right, it's probably best to keep it as simple as possible.

I just think if you branched as well you wouldn't have the hassle of having to revert commits and it would be tidier. Looking around for guides it seems like the normal work flow people use is to make a branch before modifying things.

**Comment by gb2111** [comment]
Agree. But normal practices assume that more then 1 person is working on master which is not case when you are on fork. Anyway how one work on  his or her fork is individual as you make pull reqeust anyway to cbouley.

**Comment by cboulay** [comment]
@gb2111 , here is my preferred workflow:

1. Keep your fork's master in sync with upstream master.
2. Create a new branch for a specific thing you are working on. (A bonus of this approach is that you can work on multiple unrelated things in parallel)
3. Before you make a pull request, resync your master and merge it into your branch
    * `git checkout master`
    * `git fetch upstream`
    * `git merge upstream/master`
    * `git checkout <my_branch>`
    * `git merge master`
4. If you find your pull request has a lot of nonsense commits, then rebase
    * `git rebase -i master`
    * then squash (or fixup) all the nonsense commits
    * `git push -f`. This will overwrite the commit history so it shouldn't be done on anything that may be in use by collaborators, but it's generally safe to do in a pull request.

**Comment by HipsterSloth** [comment]
@cboulay Thanks for posting this write up. I've actually been wondering how to do a rebase myself (and when that approach should be used).

**Comment by HipsterSloth** [comment]
@greg @zelmon64 I'm wondering if this might be a better value to put in the steamvr plugin here:

https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L2878-L2880

Rather than inside a specific filter inside psmoveservice. It seems like this is a useful value that you might want in general independent of which velocity filter you use? Also it seems like the amount you scale the velocity should be configurable.

What do you guys think?

**Comment by cboulay** [comment]
@HipsterSloth I edited above the rebase blurb with an important detail about conflicts.

**Comment by zelmon64** [comment]
@HipsterSloth I agree it would be nice for it to be configurable. I can work on modifying the steamvr plugin unless Greg wants to.

@cboulay it's thanks to your instruction that I've been able to rebase. My resync process is a little different but seems to work fine. I wondered if you would mind advising if there is an important difference or not:
- `git checkout master`
- `git pull upstream master`
- `git push` (to update my remote master)
- `git checkout <my_branch>`
- `git rebase master`

As you can see I don't use `merge`. Have I just been lucky that it's worked so far?

**Comment by cboulay** [comment]
@zelmon64 
Maybe we should end the conversation here because it's pretty off-topic.
But `git pull` is the same as `git fetch && git merge`. I just prefer to do it one step at a time to make the log messages easier to read.

My post has two different (confusing) ideas in it: (1) whether you want to rebase against master HEAD (to keep your commits all together) or rebase against a previous commit (to preserve timestamps relative to newer changes in upstream), and (2) whether or not there are any conflicts.

**Comment by gb2111** [comment]
But then we breake logic that driver is client of the service. It is not throwing in fact but velocity calculated by filter.


Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: Guido Sanchez <notifications@github.com> Data: 13.03.2017  17:51  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Mention <mention@noreply.github.com> Temat: Re: [cboulay/PSMoveService] throwing power adjustment after recent fixes (#388) 
@greg @zelmon64 I'm wondering if this might be a better value to put in the steamvr plugin here:
https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L2878-L2880
Rather than inside a specific filter inside psmoveservice. It seems like this is a useful value that you might want in general independent of which velocity filter you use? Also it seems like the amount you scale the velocity should be configurable.
What do you guys think?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HipsterSloth in #388: @greg @zelmon64 I'm wondering if this might be a better value to put in the steamvr plugin here:\r\n\r\nhttps://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L2878-L2880\r\n\r\nRather than inside a specific filter inside psmoveservice. It seems like this is a useful value that you might want in general independent of which velocity filter you use? Also it seems like the amount you scale the velocity should be configurable.\r\n\r\nWhat do you guys think?"}],"action":{"name":"View Pull Request","url":"https://github.com/cboulay/PSMoveService/pull/388#issuecomment-286169203"}}}

**Comment by zelmon64** [comment]
@gb2111 I think there might be some strange shenanigans going on anyway. I want ahead and had a go at adding an adjustable multiplier (to both the linear velocity and acceleration: https://github.com/cboulay/PSMoveService/commit/5d48be153a19274a9c8fa1ff17cbcba062c2ff70) and even with them set to 1.0 it seems easier to throw things.

**Comment by gb2111** [comment]
WilliamI see you moved forward with it. Are u OK to implement it to the end?Before it would be good to drop build for testing.


Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: William <notifications@github.com> Data: 13.03.2017  19:45  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Mention <mention@noreply.github.com> Temat: Re: [cboulay/PSMoveService] throwing power adjustment after recent fixes (#388) 
@gb2111 I think there might be some strange shenanigans going on anyway. I want ahead and had a go at adding an adjustable multiplier (to both the linear velocity and acceleration: 5d48be1) and even with them set to 1.0 it seems easier to throw things.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zelmon64 in #388: @gb2111 I think there might be some strange shenanigans going on anyway. I want ahead and had a go at adding an adjustable multiplier (to both the linear velocity and acceleration: https://github.com/cboulay/PSMoveService/commit/5d48be153a19274a9c8fa1ff17cbcba062c2ff70) and even with them set to 1.0 it seems easier to throw things."}],"action":{"name":"View Pull Request","url":"https://github.com/cboulay/PSMoveService/pull/388#issuecomment-286205046"}}}

**Comment by zelmon64** [comment]
@gb2111 https://drive.google.com/open?id=0B7SYYOqNW4FSam0yYXM2Z1VQbEU

**Comment by gb2111** [comment]
thankd. will try tomorrow.
just realized there is nothing on my side in such case :)
thanks!

**Comment by zelmon64** [comment]
I think there may be a problem. @maddogspeighty reported that the controllers were shaky when using `m_state->velocity_m_per_sec = prevVelocity * 2;` in the filter and I can confirm this is also the case with increasing the linear velocity in the driver.

If I instead apply the multiplier to the linear acceleration like you (@HipsterSloth) suggested it doesn't seem to have any effect on throwing but isn't shaky.

**Comment by gb2111** [comment]
i think acceleration is not calculated that is why there is no effect.
and we might try to compensate lack of acceleration with too much of velocity.
let me see if I can make simple velocity algorithm. anyway multiplier in server we can throw away.

**Comment by zelmon64** [comment]
@gb2111 I see what you mean about the acceleration being zeroed in the filter. If it's okay I had a go at copying your method for calculating the velocity and applying it to the acceleration. I can now see the yellow acceleration indicator in the test tracking part of the config tool so I think it's working. What do you think: https://github.com/zelmon64/PSMoveService/commit/3024cf4eb847ac4787c000ba95360f4c0f9457c8?

Here's a new build with it:
https://drive.google.com/open?id=0B7SYYOqNW4FSeTZ5TC01YnZqS2s

It now seems to help the throwing power but it too is making the controller model shaky.

**Comment by gb2111** [comment]
Hi.You just did it like I would  :)When I started work on throwing I put constant value 1 and it was shaking like crazy even it was put still.My next thought is to work with coefficients u created for velocity and acceleration.  Perhaps we should reduce vel speed and increase acceleration? I would also check visually how vector looks like for kalman filter  and adjust coefficient in server to be same  :)




Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: William <notifications@github.com> Data: 13.03.2017  23:28  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Mention <mention@noreply.github.com> Temat: Re: [cboulay/PSMoveService] throwing power adjustment after recent fixes (#388) 
@gb2111 I see what you mean about the acceleration being zeroed in the filter. If it's okay I had a go at copying your method for calculating the velocity and applying it to the acceleration. I can now see the yellow acceleration indicator in the test tracking part of the config tool so I think it's working. What do you think: zelmon64@3024cf4?
Here's a new build with it:

https://drive.google.com/open?id=0B7SYYOqNW4FSeTZ5TC01YnZqS2s
It now seems to help the throwing power but it too is making the controller model shaky.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zelmon64 in #388: @gb2111 I see what you mean about the acceleration being zeroed in the filter. If it's okay I had a go at copying your method for calculating the velocity and applying it to the acceleration. I can now see the yellow acceleration indicator in the test tracking part of the config tool so I think it's working. What do you think: https://github.com/zelmon64/PSMoveService/commit/3024cf4eb847ac4787c000ba95360f4c0f9457c8?\r\n\r\nHere's a new build with it:\r\nhttps://drive.google.com/open?id=0B7SYYOqNW4FSeTZ5TC01YnZqS2s\r\n\r\nIt now seems to help the throwing power but it too is making the controller model shaky."}],"action":{"name":"View Pull Request","url":"https://github.com/cboulay/PSMoveService/pull/388#issuecomment-286263641"}}}

**Comment by gb2111** [comment]
If acceleration will be too small then I would take smaller step them 20 for acceleration. But leave 20 for velocity.


Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: William <notifications@github.com> Data: 13.03.2017  23:28  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Mention <mention@noreply.github.com> Temat: Re: [cboulay/PSMoveService] throwing power adjustment after recent fixes (#388) 
@gb2111 I see what you mean about the acceleration being zeroed in the filter. If it's okay I had a go at copying your method for calculating the velocity and applying it to the acceleration. I can now see the yellow acceleration indicator in the test tracking part of the config tool so I think it's working. What do you think: zelmon64@3024cf4?
Here's a new build with it:

https://drive.google.com/open?id=0B7SYYOqNW4FSeTZ5TC01YnZqS2s
It now seems to help the throwing power but it too is making the controller model shaky.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zelmon64 in #388: @gb2111 I see what you mean about the acceleration being zeroed in the filter. If it's okay I had a go at copying your method for calculating the velocity and applying it to the acceleration. I can now see the yellow acceleration indicator in the test tracking part of the config tool so I think it's working. What do you think: https://github.com/zelmon64/PSMoveService/commit/3024cf4eb847ac4787c000ba95360f4c0f9457c8?\r\n\r\nHere's a new build with it:\r\nhttps://drive.google.com/open?id=0B7SYYOqNW4FSeTZ5TC01YnZqS2s\r\n\r\nIt now seems to help the throwing power but it too is making the controller model shaky."}],"action":{"name":"View Pull Request","url":"https://github.com/cboulay/PSMoveService/pull/388#issuecomment-286263641"}}}

**Pull request closed without merging**
