### PR TITLE
Edited Windows build scripts to work with MSVC2015, OpenCV-3.1 and boost1.61

### PR DESCRIPTION
**Pull request by cboulay**
Note that I moved the assumed boost root to its real (newish?) default directory from the self-extracting exe (C:\local\boost_1_61_0). Also updated submodules SDL2, libusb, and protobuf. Win32 PSMoveService configures won't work because precompiled OpenCV is missing 32-bit binaries. We could still build a 32-bit client but this isn't desirable because steamvr server defaults to 64-bit.

We have to build OpenCV ourselves if we want to work with CLEyeMulticam.dll. I'm now downloading all the dependencies for the optimized OpenCV builds on my system, but the intel ones are only available for free for academics, though we can distribute things linking them (I'm pretty sure). I'll try to build unoptimized for now. Don't merge this yet until I can confirm that I can build OpenCV unoptimized.

### CODE REVIEW

**Comment by cboulay** [comment]
I was able to build OpenCV and point to it during PSMoveService's cmake configure steps but building PSMoveService x86 failed at linking OpenCV because some symbols were missing. It's possible I didn't configure OpenCV's build with all the right options (there are a lot of them!). It's also possible that there's a mismatch between the binaries I built from the latest opencv from github and the include files I used from OpenCV's precompiled download (I moved my built binaries next to the downloaded binaries in C:\OpenCV-3.1.0).

I can try building again next week, or you can try.

**Comment by cboulay** [comment]
OK it's actually possible to build OpenCV in the folder that comes with the precompiled binaries. Configuring in that folder/build with cmake will generate `OpenCVConfig.cmake`. If we add that path to the CMAKE_MODULE_PATH then cmake will search there when doing find_package(OpenCV) and it will know the correct directory structure.

The only gotcha with this method was that the list(APPEND CMAKE_MODULE_PATH) command didn't like C:\OpenCV-3.1.0\build, it needed C:/OpenCV-3.1.0/build. As this path comes from the SetBuildVars.bat, the script that builds SetBuildVars.bat needs to be fixed. Maybe. This should be checked.

@HipsterSloth Can you give this a try?

**Comment by HipsterSloth** [comment]
Sure thing. I can fix the InitialSetup.bat script and give that a test tonight.

**Comment by HipsterSloth** [comment]
I just made a few small fixes to the build batch scripts. Most importantly I was able to build OpenCV from source in 32-bit and point the OPENCV_BUILD_PATH to C:/OpenCV-3.1.0/sources/build/install. I updated the InitialSetup_Win32.bat to automatically build the opencv project files and then build from source. With these changes I was able to successfully build both 32-bit and 64-bit builds from scratch using MSVC2015, OpenCV3.1 and Boost 1.6.1. Hooray! \o/

**Comment by cboulay** [comment]
I wonder if we can get the 64-bit and 32-bit builds to live side-by-side in C:/OpenCV-3.1.0/build (i.e., the default folder used by the 64-bit build). I can't remember, but I think the 64-bit precompiled binary download doesn't have a OpenCVConfig.cmake file so we don't have to worry about stomping on that. The self-build of the 32-bit binaries doesn't distinguish the lib names from the 64-bit build but it does keep them in separate folders, so that should be fine.

Also, you can reduce the compile time of OpenCV A LOT by unselecting some unneeded options when cmake'ing it.

**Comment by cboulay** [comment]
We also need to add 64-bit debug builds to the OpenCV-3.1.0/build

**Comment by HipsterSloth** [comment]
Sorry I left the build script changes languishing. I just did some work on this today.

>I wonder if we can get the 64-bit and 32-bit builds to live side-by-side in C:/OpenCV-3.1.0/build (i.e., the default folder used by the 64-bit build).

> Also, you can reduce the compile time of OpenCV A LOT by unselecting some unneeded options when cmake'ing it.

I just updated the InitialSetup_Win32.bat script to do the following:
* Copy 32-bit OpenCV build from %OPENCV_ROOT_PATH%/sources/build/install/x86 to %OPENCV_ROOT_PATH%/build (along side x64 build)
* Clean up OpenCV build intermediates after build completes
* Setting the OPENCV_BUILD_PATH back to %OPENCV_ROOT_PATH%/build
* Turned off unnecessary OpenCV features to improve build times

> We also need to add 64-bit debug builds to the OpenCV-3.1.0/build

Is the 'OpenCV-3.1.0\build\x64\vc14\lib\opencv_world310d.lib' that comes with the OpenCV 3.1 download not the debug build?

**Comment by HipsterSloth** [comment]
@cboulay In preparation for making the next release and getting the DS4 work up to master I went ahead and merged this pull request. 

Unfortunately when I was making the new release last night I noticed  that the newly built PSMoveService started requiring the OpenCV DLLs. I thought we were statically linking against OpenCV, but I decided to copy over the needed DLLs and just see what happens. This led to a heap assert related to std::vector allocated on the stack in the PSMoveService exe, but whose contents is filled out inside the OpenCV DLL (generating a contour). If the EXE is using the static C runtime (which we are) each DLL will have it's own heap. In this instance, the EXE is trying to free memory from the DLL heap, which caused the assert.

So I think we still want to have OpenCV statically linked. It looks like the 3.1 release of OpenCV doesn't generate the static libs by default anymore (no `staticlib` in `C:\OpenCV-3.1.0\build\x64\vc14`, only `lib` which is for the DLL based linkage.  This means I would need modify the InitialSetup script to build x64 build (in addition to the Win32). Any objections to this?

**Comment by cboulay** [comment]
As the pre-compiled OpenCV download is now useless to us, now might be the time to start using ExternalProject. [Here](https://github.com/arnaudgelas/ExternalProject/blob/master/External-OpenCV.cmake)'s an OpenCV example. [Here](https://github.com/sfwa/ukf/blob/master/CMakeLists.txt#L19-L34)'s an Eigen example.

**Comment by HipsterSloth** [comment]
Thanks for the links! I'll give that a try tonight and let you know how that goes.

**Comment by HipsterSloth** [comment]
So the external project thing was throwing me for a loop. I was getting errors with the Find_Package(OpenCV) command when trying to generate the project files. I had assumed that generating the project file would download and build external project. However, after looking at this  cmake file that uses external projects: http://gauss.cs.ucsb.edu/svn/kdt/trunk/CombBLAS/graphlab_cmakelists.txt, I realized that external projects do that work when building your project, not during project file generation. This means that FindPackage is incompatible with external projects (since the project won't be built yet).

Did you want to switch other platforms to building OpenCV as an external project or did you want to keep using FindPackage for those?

I was able to get the project file generating with OpenCV as an external project. When building the external project it pulls down the project from git, builds it and installs it into {project_root}/deps/local/. The problem I'm having now is that the opencv libs need a different suffix depending on release (...310.lib) or debug (310d.lib). I tried to do this DEBUG/RELEASE_POSTFIX cmake property but it doesn't seem to work for me. Does this look right to you:

```
IF(NOT OpenCV_DIR)
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    ExternalProject_Add(opencv
      PREFIX ${ROOT_DIR}/deps/opencv
      GIT_REPOSITORY https://github.com/opencv/opencv.git
      GIT_TAG 3.1.0
      CMAKE_GENERATOR ${gen}
      CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DBUILD_WITH_STATIC_CRT:BOOL=ON
        -DBUILD_SHARED_LIBS:BOOL=OFF
        -DBUILD_DOCS:BOOL=OFF
        -DBUILD_EXAMPLES:BOOL=OFF
        -DBUILD_PACKAGE:BOOL=OFF
        -DBUILD_TESTS:BOOL=OFF
        -DBUILD_PERF_TESTS:BOOL=OFF
        #-DCMAKE_BUILD_TYPE:STRING=Release
        -DWITH_FFMPEG:BOOL=OFF       
        -DWITH_OPENEXR:BOOL=OFF
        -DWITH_JASPER:BOOL=OFF
        -DWITH_TIFF:BOOL=OFF
        -DWITH_IPP:BOOL=OFF
        -DBUILD_NEW_PYTHON_SUPPORT:BOOL=OFF
        -DBUILD_opencv_apps:BOOL=OFF
        -DBUILD_opencv_calib3d:BOOL=ON
        -DBUILD_opencv_flann:BOOL=ON
        -DBUILD_opencv_features2d:BOOL=ON
        -DBUILD_opencv_objdetect:BOOL=ON
        -DBUILD_opencv_photo:BOOL=ON
        -DBUILD_opencv_ts:BOOL=OFF
        -DBUILD_opencv_ml:BOOL=ON
        -DBUILD_opencv_video:BOOL=ON
        -DBUILD_opencv_java:BOOL=OFF
        -DBUILD_opencv_python2:BOOL=OFF
        -DBUILD_opencv_python3:BOOL=OFF
        -DCMAKE_INCLUDE_PATH=${ROOT_DIR}/deps/local/include        
        -DCMAKE_LIBRARY_PATH=${ROOT_DIR}/deps/local/lib        
      INSTALL_DIR ${ROOT_DIR}/deps/local/
    )
    add_definitions(-DHAS_OPENCV)
    list(APPEND OpenCV_LIBS opencv_core opencv_imgproc opencv_calib3d opencv_video opencv_features2d opencv_ml opencv_highgui opencv_objdetect)
    set(OpenCV_DIR ${ROOT_DIR}/deps/local/lib)
    set(OpenCV_INCLUDE_DIRS ${ROOT_DIR}/deps/local/include )
    set_target_properties(opencv PROPERTIES RELEASE_POSTFIX "310")
    set_target_properties(opencv PROPERTIES DEBUG_POSTFIX "310d")
ELSEIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    # Location of homebrew opencv3
    # Alternatively, can do `brew ln opencv3 --force`
    message("-- Using homebrew opencv3")
    set(OpenCV_DIR "/usr/local/Cellar/opencv3/3.1.0_1/share/OpenCV")
ENDIF()#Windows or Darwin
ENDIF(NOT OpenCV_DIR)
```

**Comment by HipsterSloth** [comment]
I finally got this compiling in Win32|Debug. I checked in the updated build scripts: c28f045ef55c28c25cac2f77ff96c3711c6fd0ca

I get this wierd cmake error when I try to build the opencv external project in Win32|Release after trying to build debug:

```
1>------ Build started: Project: opencv (ExternalProjectTargets\opencv\opencv), Configuration: Release Win32 ------
1>  Building Custom Rule E:/git-cboulay/PSMoveService_master/CMakeLists.txt
1>  CMake does not need to re-run because E:\git-cboulay\PSMoveService_master\build\CMakeFiles\generate.stamp is up-to-date.
1>  Creating directories for 'opencv'
1>  Performing download step (git clone) for 'opencv'
1>  -- Avoiding repeated git clone, stamp file is up to date: 'E:/git-cboulay/PSMoveService_master/deps/opencv/src/opencv-stamp/opencv-gitclone-lastrun.txt'
1>  Performing update step for 'opencv'
1>  No patch step for 'opencv'
1>  Performing configure step for 'opencv'
1>  CMake Error at cmake/OpenCVDetectPython.cmake:78 (if):
1>    if given arguments:
1>
1>      "NOT" "optimized" "C:/Python27/libs/python27.lib" "debug" "C:/Python27/libs/python27_d.lib" "EQUAL" ""
1>
1>    Unknown arguments specified
1>  Call Stack (most recent call first):
1>    cmake/OpenCVDetectPython.cmake:219 (find_python)
1>    CMakeLists.txt:562 (include)
```

Going to look more into that tomorrow and then make sure the 64-bit build works as well.

**Comment by HipsterSloth** [comment]
I was able to hack around the python issue (acually a bug in their cmake script for finding python2) by providing a path to the python lib in question. It's a no-op because we don't end up actually compiling python support for OpenCV later in the OpenCV cmake script. I got both Win32 and X64 builds compiling again. Making a new release as I type this.

**Pull request merged**
