### PR TITLE
improve CPU utilisation by adding timeout to main thread loop

### PR DESCRIPTION
**Pull request by gb2111**

### CODE REVIEW

**Comment by cboulay** [comment]
So, why does this improve CPU utilization? Presumably this would only work if there was a busy wait somewhere downstream of this... where is the busy wait?

Does this add any latency?

I don't have time to go through the whole PSMoveService logic right now, but I'm really hesitant to think that simply adding a sleep is a good idea. If you can isolate where the busy wait is then we should fix it there.

**Comment by HipsterSloth** [comment]
@cboulay It's not actually adding a new sleep but instead adding a configurable value to an existing sleep in the main loop. The original value in that sleep was 1ms, which I think I might have left in as experimently low value and forgot to take out (it probably should be like 5ms at a minimum). I agree that we should understand where the busy waiting is occurring (maybe in the camera frame polling?), but seeing as how this PR doesn't actually change any existing functionality and it can help some people who were having CPU usage issues I think it's a useful knob to add in for the time being. 

When I tested an earlier version of the change I got nearly the same update frame rate on the console test client when this sleep was 20ms instead of 1ms and the CPU usage dropped from 25-30% down to 15%.

@gb2111 I think we should keep the default at 1ms just to keep the behavior the same for now until we understand more deeply where busy-waiting is occurring.

**Comment by cboulay** [comment]
60 Hz = 16.6666 msec per frame, so sleeping 20 msec necessarily misses every other frame and therefore I would hope that would get you a significant speedup.

If there's no difference between 1 and X (X = 16 msec - frame processing time) then this is probably not doing anything other than missing frames.

Also `boost::this_thread::sleep` is [deprecated](http://www.boost.org/doc/libs/1_53_0/doc/html/thread/thread_management.html#thread.thread_management.this_thread.sleep) and should be replaced with `boost::this_thread::sleep_for`, or better yet, [`std::this_thread::sleep_for`](http://en.cppreference.com/w/cpp/thread/sleep_for).

**Comment by HipsterSloth** [comment]
> 60 Hz = 16.6666 msec per frame, so sleeping 20 msec necessarily misses every other frame and therefore I would hope that would get you a significant speedup.

That... is an excellent point. I am embarrassed I missed that. Though that does make me wonder why I was getting around 30fps when testing on my machine with the 1ms sleep (maybe I tested with a debug build?).

I any event, I still think it's still worth having a configurable value there. If a user really wants to run at a slower frame rate to get a game running I think that's a reasonable knob. It's also helpful for debugging. The filtering code takes in the time between updates and can handle variable frame rates.

> Also boost::this_thread::sleep is deprecated and should be replaced with boost::this_thread::sleep_for, or better yet, std::this_thread::sleep_for.

Also a good point. My vote is for std::this_thread::sleep_for. I'd like to slowly keep working toward removing dependence on boost libraries, particularly for functionally that already exist in the standard library.

**Comment by cboulay** [comment]
@gb2111 ,
Please switch to using `std::this_thread::sleep_for` (which will also require converting the time argument to a `std::chrono::duration`).
Please add a comment to the sleep_for line like `//TODO: Find out if there is a downstream busy wait`.
Please change the parameter name from `thread_timeout_ms` to something like `tracker_sleep_ms`, which indicates that it is being used by the tracker exclusively and that it isn't a timeout. A "timeout", to me, is the amount of time a process is allowed to work on something before it must return, even if that means returning without a complete result. Here you aren't limiting the tracker processing time at all, and might even be lengthening it.

@HipsterSloth , does the `#include "TrackerManager.h"` to PSMoveService.cpp add any awkward dependencies that we'd like to avoid, maybe creating a circular dependency in the future when we add in other features we're interested in? I haven't thought about this at all, but I'm always going to ask this question whenever I happen to notice a PR with more includes.

**Comment by HipsterSloth** [comment]
> Does the #include "TrackerManager.h" to PSMoveService.cpp add any awkward dependencies

Good question. I didn't see any circular dependencies, but I have mixed feeling about "PSMoveProtocol.pb.h" getting pulled in (ultimately due to DeviceTypeManager::getListUpdatedResponseType). I think that could come as part of another refactor. I actually have another task for cleaning up some unwanted dependencies in PSMoveService.cpp in this issue: https://github.com/cboulay/PSMoveService/issues/39

**Pull request closed without merging**
