### PR TITLE
PSMove battery information

### PR DESCRIPTION
**Pull request by zelmon64**
About a month ago I tried to feed the battery information into SteamVR. This didn't work I believe because of the OpenVR SDK update. With the C-API changes coming I thought I'd submit this as it all works apart from viewing the battery level in SteamVR.

There have been so many changes since I did this that the merge was a bit messy and I can't seem to rebase my cleanup (it keeps giving an error). Is it okay to merge this as it is or should I try some more to tidy up the commits (or are there other problems with it)?

### CODE REVIEW

**Comment by HipsterSloth** [comment]
Thanks for work on this Zelmon! 

I think what I'll do is manually copy over the changes you have here into master (hopefully tonight?). Then I'll pull them down into the capi branch and add the C-API wrapper for them. Once that's done I'll put a link to my change here to make sure it jibes with what you had in mind. Then we'll close this PR.

**Comment by HipsterSloth** [comment]
How does this look to you Zelmon:

https://github.com/cboulay/PSMoveService/commit/de609086592e8f4a5b03d6d19957c30e50cd302b

I think it's working, but I only tested this when my controller battery was fully charged.

**Comment by zelmon64** [comment]
@HipsterSloth it looks good. I like how you've set it up as an enum on the client side and how you've given out nicer words than what psmoveapi used. 

Like I said, I don't think the battery level is called properly by the OpenVR driver because it needs the SDK update. I tried all sorts of thinks like setting it to halve the battery level every time it checks it and also setting the trigger value as the level. I even made a simple Unity game that displayed the battery level as a percentage but it never changed it's value. It only seemed to read the battery level once at the start when IsValid() would give false. That being said, I think what you have put for it should work great when it's updated (and maybe is already working so what I'm rambling about is null).

Thanks for doing this, I'll close this PR now.

**Comment by zelmon64** [comment]
@HipsterSloth I compiled your CAPI branch to see if SteamVR is reading the battery or not. My controller was blinking but the SteamVR status windows still said it was full. 

I checked test_psmove_controller as well and that said 40%. It works but I'm not sure at what percentage the controllers are supposed to flash for. This was something I wondered about before but forgot to look into and I assumed psmoveapi has it correct. It just seems strange that the low battery warning would be triggered by the 40% mark instead of the 20% but I can't find any information about it.

**Pull request closed without merging**
