### PR TITLE
Mac os fixes

### PR DESCRIPTION
**Pull request by cboulay**
I have a PR in libstem_gamepad (https://github.com/ThemsAllTook/libstem_gamepad/pull/11). Until that's merged we'll have to point to my fork of it.

### CODE REVIEW

**Comment by cboulay** [comment]
Any testers? @HipsterSloth , @zelmon64 , @gb2111

**Comment by zelmon64** [comment]
@cboulay Unfortunately I'm away from my computer for the next couple of days so I can't test it right away. Sorry.

**Comment by HipsterSloth** [comment]
I'm syncing / building now on my work machine and let you know shortly if there are any compile issues. I'll do a test at home tonight and make sure the navi support still works.

**Comment by HipsterSloth** [comment]
I'm getting this error when cloning the MacOS_fixes branch: 

Unable to checkout 'd655d32413a8a4fc201476b888f5bb9c94e36d07' in submodule path 'thirdparty/libstem_gamepad'

I noticed that the .gitmodules files is still pointing at:
https://github.com/ThemsAllTook/libstem_gamepad.git 

Should I fix that locally or have you check in the update .gitmodule file?

**Comment by cboulay** [comment]
Sorry about that. It should be fixed now.

**Comment by HipsterSloth** [comment]
Looks like this compiled and worked in windows. I was able to test out two psmove controllers with two psnavi controllers in space pirate trainer. All of these changes look reasonable to me.

**Comment by HipsterSloth** [comment]
Also I left the branch around post merge in case you wanted to do any other mac os related work.

**Comment by zelmon64** [comment]
@cboulay just to say I gave the current master (45f3f6a0e6ca59444e7c4e064a8595b2a4001f2f) a quick test and didn't notice any problems.

**Pull request merged**
