### PR TITLE
Use cv::undistortPoints. Use image ROI.

### PR DESCRIPTION
**Pull request by cboulay**
This affects #50, #115 (because using cv::undistortPoints means arbitrary cameras can be used, as long as they have been calibrated).

FYI, using the ROI can speed up tracking calculations 10-20 fold depending on how much of the screen is encompassed by your ROI.

Don't merge this yet. It will likely break any HMD or DS4 tracking.
@HipsterSloth , can you implement these changes for those devices?

After you do that, you or I need to clean up some other things that I left because I didn't know how they would affect your tracking.

For instance, sometimes 3D objects are getting projected onto the image using the default coordinate system (0,0 in the corner), but other times they are getting projected onto the image using the coordinate system with 0,0 in the centre. I'm using the former (0,0 in corner) for all my debug drawings and for calculating the ROI, but you're using the latter for some things.

Because of this discrepancy, the way the camera intrinsics and distortion coefficients are retrieved is a bit haphazard. Some functions use one method, some use another. There doesn't appear to be much logic behind it. I would like to clean this up but I can't until the HMD and DS4 parts are finished.

### CODE REVIEW

**Comment by HipsterSloth** [comment]
I just checked in a fix for the ROI computation for DS4 and PSVR. The bounds computed appear to work for  the DS4. I can't test PSVR yet, because I still haven't finished implementing the optical tracking for that headset. 

I didn't have a chance this evening to look into any of clean up tasks you mentioned.

**Comment by cboulay** [comment]
FYI I'm doing the cleanup now.

There are some things I can't do.
* Light bar tracker isn't using undistortPoints.
* HMD tracking does not use ROIs or undistortPoints.

I'll post here when I'm done. We can still merge without the above changes when I'm done if you think you can't get to these anytime soon.

**Comment by HipsterSloth** [comment]
I'm happy to fill those pieces in tonight/tomorrow. I was planning on working on psmoveservice stuff  on and off all this weekend.

**Comment by cboulay** [comment]
It's always nice to have a commit with 50% more deletions than additions.

So the general cleanup that I tried to do and I hope can be completed in the rest of the file is...

* camera parameters are always retrieved with `computeOpenCVCameraIntrinsicMatrix`. I had to change the function signature because it has 2 outputs now.
* always use undistortPoints and projectPoints where possible.
    * All of the manual handling of +screen_width/2 etc shouldn't be necessary.

**Comment by HipsterSloth** [comment]
Thanks for spearheading this cleanup and ROI work! I picked up the baton this evening and carried it a bit further. 

The undistortion code had been applied to the DS4 and the PSVR point cloud tracking code. I also moved the ROI computation code into it's own function so that it could be called in both the controller and the hmd optical pose estimation code. While testing these changes I ran into issues with the final part of the ROI bounding box calculation being incorrect (never followed the controller). I tweaked it a be a bit more explicit in how it computes the extents and upper left hand corner of the ROI box. It appears to work correctly now for the PSMove and the DS4 (and only takes 10% CPU for two cameras!). 

Here's all the remaining related work I can think of (some of this can happen after the merge to master):
* Still need to clean up more of the manual +screen_width/2 code. I got a few places, but there are a bunch more. 
  - Are you ok with redefining CommonDeviceScreenLocation to mean a pixel location in the range [0,0]->[width, height]?
  - It currently is interpreted as [-width/2, -height/2]x[width/2, height/2]  and that's inconsistent with how it's being used now.
* Need to get rid of the debug rendering in the config tool that draws the tracking projections since that's now effective done on the server
* Need a client side toggle for showing/hiding tracking contour debug rendering
* Need an option to not use ROI when starting a controller stream
  - When the camera poses haven't been computed yet (or are wrong) you can't use the pose filter's estimate to compute a reliable ROI anymore
  - Need to suppress ROI during the camera pose calibration tool
* Need a debug switch to disable ROI in TrackerManagerConfig and maybe settable the client UI too
* ROI window size should be tunable (rather than hard coded to x2
* We need to play with state prediction 
  - Pass a non-zero prediction time into ROI box computation
  - Currently it's pretty easy with the Kalman position filter active to overshoot the ROI window
* We should move ROI testing into the tracking test tool (i.e. not rely on camera pose calibration tool)
  - Add camera ID label next to each frustum in the test tracking window
  - Add a button next to the tracker entry in the tracking status panel to show the video feed from that tracker
  - This video feed view will have the toggle for the ROI debug rendering

**Comment by cboulay** [comment]
That all sounds good.

|Are you ok with redefining CommonDeviceScreenLocation to mean a pixel location in the range [0,0]->[width, height]?

Yes, that's good. As long as everything is using the same convention.

About the need to disable the ROI when the camera poses have not been calibrated yet, does this only apply to multi-cam setups? Because with a single camera, the default world-to-camera transform might not be correct, but it shouldn't break anything. The only problem, I think, would be when the position is estimated using incorrect triangulation. But anyway, I think many users are using multiple cameras so this is something that needs to be done before merging into master. BTW, disabling the ROI should be as easy as using the default full-frame ROI.

I think that and the remaining cleanup/consistency are all that needs to be done before merging into master. The rest can be done later.

I'll do a little work on PSMoveService tonight but not until after 9pm EST. I plan to work on Matlab stuff and maybe the CAPI a little so you don't have to worry about us stepping on each other's toes.

**Comment by HipsterSloth** [comment]
I did the following this evening:
* Clean up the remaining of the manual +screen_width/2 code. 
* Got rid of the debug rendering in the config tool that draws the tracking projections since that's now effective done on the server
* Added an controller_start_stream flag to disable ROI 
  - This is used to suppress ROI during the camera pose calibration
* Added TrackerManagerConfig global "disable_roi" option
  - This is currently true by default, specifically for the release I make this Sunday. I want people to opt into the new feature and test it out. As soon as we get any as-yet-unknown bugs/issues worked out I'll change the default to false.
* Move ROI testing into the tracking test tool (i.e. not rely on camera pose calibration tool)
 - Added camera ID label next to each frustum in the test tracking window
 - Add a button next to the tracker entry in the tracking status panel to show the video feed from that tracker

With this work done I feel good about merging the ROI work to master. I still have a few more polish items and bug fixes to do for the release I want to put on on Sunday, but those are best done in master at this point. I'm going to merge this PR now in prep for tomorrows work.

BTW the remaining master branch clean-up work I was planning to do tomorrow was the following:
*  Fix controller index crash in SteamVR driver
 * Fix bug with temp exposure/gain override in distortion calibration
 * Fix bug with wrong controller model sometimes showing up in SteamVR
 * Actually update the focal lengths and distortion parameters in PS3EyeTracker::setOptionIndex (red/blue option setting)
  * Add warning/reset defaults option for distortion calibration tool when used on ps3eye trackers
  * Kalman filter tuning Q/R tuning weights in UI
  * Add proper DualShock4 controller models in SteamVR

**Pull request merged**
