### PR TITLE
allowing skip certain no of tracker processing to improce orientation responsivness

### PR DESCRIPTION
**Pull request by gb2111**
add parameter optical_tracker_skip_frames to allow skip configured number of 
m_tracker_manager->poll(); 
allowing to processs more other elements.
this improves orientation responsiveness. 
zelmod tested it as well and he confirms.
it can have negative impact on position tracking so one use it at his or her own risk.
for me with parameter 15 benefits are great!

### CODE REVIEW

**Comment by cboulay** [comment]
This is the wrong solution to this.
Instead the camera polling and sensor (bluetooth) polling should be asynchronous.

Some of the reasons why I don't like it:

* We already have too many parameters and settings. I would prefer less, not more.
* It has no concept of frame rate. Skipping N frames at 30 fps is different than skipping N frames at 60 fps. This is an added unnecessary complication that someone would need to add to the documentation and answer questions on in the forums.

**Comment by gb2111** [comment]
Hi Chad.The approach u are proposing is not something I can undertake at the moment.This solution is dirty but it works so well and I am really amazed what really justifies doing it. It's default 0 so no impact.Other topic is that I don't think that we can have less parameters since there is so many cases and it's so far away from out of box solution...
And once more... it really does work perfectly.


Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: Chadwick Boulay <notifications@github.com> Data: 01.03.2017  21:14  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Author <author@noreply.github.com> Temat: Re: [cboulay/PSMoveService] allowing skip certain no of tracker processing to improce orientation responsivness (#375) 
This is the wrong solution to this.

Instead the camera polling and sensor (bluetooth) polling should be asynchronous.
Some of the reasons why I don't like it:

We already have too many parameters and settings. I would prefer less, not more.
It has no concept of frame rate. Skipping N frames at 30 fps is different than skipping N frames at 60 fps. This is an added unnecessary complication that someone would need to add to the documentation and answer questions on in the forums.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cboulay in #375: This is the wrong solution to this.\r\nInstead the camera polling and sensor (bluetooth) polling should be asynchronous.\r\n\r\nSome of the reasons why I don't like it:\r\n\r\n* We already have too many parameters and settings. I would prefer less, not more.\r\n* It has no concept of frame rate. Skipping N frames at 30 fps is different than skipping N frames at 60 fps. This is an added unnecessary complication that someone would need to add to the documentation and answer questions on in the forums."}],"action":{"name":"View Pull Request","url":"https://github.com/cboulay/PSMoveService/pull/375#issuecomment-283456331"}}}

**Comment by cboulay** [comment]
"Works perfectly" seems to be subjective. In my view, needing to skip frames is not "working perfectly".

What is the underlying problem? Please take the time to describe it clearly.

If I understand correctly, the high-level problem is that polling the cameras is taking too long and this is slowing down everything else. WHY is it taking too long? What's the bottleneck? Why can't this be solved by reducing the camera framerate? Is there a busy wait somewhere while it waits for a frame to be available? If so, then wouldn't the better solution to be to check if the camera has a frame available and if not then `poll()` should return immediately? Then users only have to turn one knob (camera fps).

**Comment by ZedVR** [comment]
@gb2111 Hey! I am having the same issue, and would like to try out your solution!
Could you help me please, where should I exactly put in "optical_tracker_skip_frames" and "m_tracker_manager->poll();" ?
Thank you in advance!

**Comment by Eerovil** [comment]
@ZedVR I've made a fork with the changes here: https://github.com/Eerovil/PSMoveService

Haven't tested yet, I'll need to setup a build environment first...

**Pull request closed without merging**
