### PR TITLE
Dualshock4

### PR DESCRIPTION
**Pull request by HipsterSloth**
Initial support for the DualShock 4 controller
------------------------------------------------
The DualShock 4 controller is now supported as one of the valid tracked controller types. All buttons and rumble states are accessible to the client (including steamvr plugin). The tracking is still in pretty rough early state. The 'ControllerPositionEstimation ' struct has been replaced with a 'ControllerOpticalPoseEstimation' since the optical pose estimate can now compute the orientation of the tracking shape (if it's the new "lightbar" tracking shape). There is a new framework in place for blending between optical tracking and IMU tracking using an optical tracking metric (see issue #72). This will get rolled into the Kalman filter work in some form or another.

I'll post a video with more details about all the work that went into these changes later tonight.

### CODE REVIEW

**Comment by HipsterSloth** [comment]
I did a bunch of testing (testing multiple controllers, new calibration tools, tracker calibration, etc) to make sure I didn't break any existing psmove controller support. I need to merge this into master so that I can start the integration of these changes into the CAPI branch tomorrow. 

Also the explanation video for this PR is going to take me another night to finish. I'll post a link to that in here when I finish here for reference.

**Comment by zelmon64** [comment]
@HipsterSloth We all know how difficult it is to estimate a work flow and I for one am very impressed by your progress!

I managed to build this (using msvs 2015) and have some thoughts if you like:
* I was caught out by the new OpenCV implementation. Building took so long for me because my dl speed is only 3.4 Mbps. Could some kind of progress bar be added so that you know it's downloading and hasn't just crashed? I used the task manger to check my network usage so I knew it was still downloading.
* I noticed the colour calibration for the DS4 needs different values than the PSMove (at least in my set up). I wondered if two sets of colour information could be saved.
* The only time the Steam controller model showed in SteamVR it was representing one of the PSMove controllers. The DS4 never had a model (verified by seeing nothing at the end of the laser pointer).
* The new accelerometer calibration works but nothing happens in the test screens for either the DS4 or the PSMoves.
* To make navigating the the calibration tool easier would it be possible to always show the next and previous buttons and after editing a setting for a specific controller or tracker can the screen return to that device's subscreen?
* Finally I noticed the lag during the tracker pose calibration some people have mentioned and it was because the CPU usage was very high. Luckily for me I could just stop something that I normally have running that used about 20%. Do these latest changes require more CPU power (like the DS4 tracking perhaps)?

I hope some of these thoughts might help.
(attached my build if anyone else wants a go)
[PSMS-6ca7793.7z.001.zip](https://github.com/cboulay/PSMoveService/files/408825/PSMS-6ca7793.7z.001.zip)
[PSMS-6ca7793.7z.002.zip](https://github.com/cboulay/PSMoveService/files/408824/PSMS-6ca7793.7z.002.zip)

**Comment by HipsterSloth** [comment]
@zelmon64 Thanks for slogging through the setup process and giving this a test! Responses inline:

> Building took so long for me because my dl speed is only 3.4 Mbps. Could some kind of progress bar be added so that you know it's downloading and hasn't just crashed?

Sorry about that. Getting OpenCV compiling with MSVC 2015 has been a painful transition. In OpenCV3.1 the binary installer no longer has the pieces we need to build psmove service in the configurations we want. This meant having to download and build opencv from source. In the past this required the user to manually pull down OpenCV into the right place and build it yourself. We didn't want to go back to that, so we decided to give cmake's [External Project](https://cmake.org/cmake/help/v3.1/module/ExternalProject.html) command a try as part of the build scripts. That command will auto-download and compile OpenCV as part of the PSMoveService project's build. I assume you saw the same output when building OpenCV?

```
2>------ Build started: Project: opencv (ExternalProjectTargets\opencv\opencv), Configuration: Debug x64 ------
2>  Building Custom Rule C:/cboulay-git/PSMoveService_master/CMakeLists.txt
2>  CMake does not need to re-run because C:\cboulay-git\PSMoveService_master\build\CMakeFiles\generate.stamp is up-to-date.
2>  Creating directories for 'opencv'
2>  Performing download step (git clone) for 'opencv'
2>  Cloning into 'opencv'...
   <long wait>
2>  Checking out files:   8% (387/4792)
2>  Checking out files:   9% (432/4792)
...
```

Unfortunately, there is no option I could find for the external project command that display download progress for the git download. There is a 'LOG_DOWNLOAD 1' option but it doesn't appear to do anything when set :/. There might some way to accomplish the download step with a custom build step, but my cmake kung-fu is weak.

> The DS4 never had a model (verified by seeing nothing at the end of the laser pointer).

Who has two thumbs and forgot to check in `dualshock4_controller.obj`?


I keep forgetting that .obj is in the .gitignore list.

> I noticed the colour calibration for the DS4 needs different values than the PSMove (at least in my set up). I wondered if two sets of colour information could be saved.

Yeah I noticed that yesterday too when testing having both DS4 and PSMoves at the same time that the yellow color I calibrated on the PSMove didn't work for the DS4 tracking. We absolutely could save an alternate set of color configs per controller. I hadn't bothered with it yet because the use case we have here at work will only be using the ds4 controller, but that does need to get fixed before people can broadly use this. I'll try to get to that before the end of the week. It's not a hard change fortunately (mostly just some UI and plumbing).

> The new accelerometer calibration works but nothing happens in the test screens for either the DS4 or the PSMoves.

Sorry I should have talked about how this works in the release notes. The PSMove won't give any valid linear acceleration data back at the moment (intentionally zero'd out) until the the Kalman filter is done. The linear acceleration I was computing before was too noisy. As for the DS4, you will only see the linear acceleration show up once the camera has seen the light bar at least once. This is an odd quirk of how I have positional filter operating. This will also get fixed as I continue to work on the DS4.

> To make navigating the the calibration tool easier would it be possible to always show the next and previous buttons and after editing a setting for a specific controller or tracker can the screen return to that device's subscreen?

Absolutely. That was driving me crazy yesterday too. I'll fix that now.

> Do these latest changes require more CPU power (like the DS4 tracking perhaps)?

Yeah I think my usage of cv::SolvePnP to get the ds4 pose isn't cheap (doing an iterative solve of a non-linear optimization problem). I have another approach I want to try when using multicam that will allow me to use triangulation to solve the pose instead of SolvePnP. It should definitely be cheaper and hopefully more reliable. The single camera case will still have to use SolvePnP, but hopefully because one is only using one camera in that case the perf hit won't be so bad. 

Also the CPU should should only happen when using the DS4. There shouldn't be any new perf hit if you are just using the PSMove. But if there is an unexpected perf hit, I'd love to know.

This was very helpful. Thanks a bunch for trying this out and writing this up! I'm going to continue working on DS4 tracking over the next week or two. Hopefully I can get it to a somewhat usable state. I'll take care of the simple stuff today and then make an official release tomorrow along with the video.

**Comment by cboulay** [comment]
>That command will auto-download and compile OpenCV as part of the PSMoveService project's build.

In the external project you can override the `DOWNLOAD_COMMAND` and use `git clone --depth 1` so the OpenCV download is much smaller.

**Comment by cboulay** [comment]
Oh, even better, you can just add `GIT_SHALLOW 1` without overriding the download_command. This is a fairly new feature... trying to find the version now...

**Comment by HipsterSloth** [comment]
Looks like [3.6](https://cmake.org/cmake/help/v3.6/release/3.6.html). Giving that a try now...

**Comment by HipsterSloth** [comment]
It looks like it worked? I deleted cmake and grabbed cmake 3.6.1, then cleared out the /deps folder and the /build folder. I didn't see any change in output, but I think it downloaded a bit faster for me? My download is pretty quick for me, so it's hard to tell.

**Comment by HipsterSloth** [comment]
I just checked in fixes for the open cv build thing, adding the missing controller model, remembering which controller/tracker you had selected when switching between menus, and finally the per controller color filter settings (see Issue #95). I did some initial testing on the per controller filtering, but it's possible I missed some edge cases so let me know if you run into any issues or have feedback on the implementation. I'll hold back on pushing a release out until that get's tested by someone else since I don't want to ship broken color filter tools.

**Comment by HipsterSloth** [comment]
Part 1 of the video explaining this changes is up: 

[DS4TrackingPt1](https://youtu.be/ywxjFAQuxkQ "DS4TrackingPt1")
 
For @cboulay most of the stuff in part 1 is stuff you already know very well, but gives context for part 2 that I'm going to finish tomorrow. This video covers motivation for doing this work, differences between tracking the PSMove and the DualShock4, and trying to calibrate the accelerometer values. Part 2/2 will cover calibrating the gyroscope, extracting the optical pose of the controller, showing the tracking progress so far in steamvr and the future work I have planned.

Let me know if you guys have any questions or corrections for the video.

**Comment by zelmon64** [comment]
@HipsterSloth I updated to cmake 3.6.1 and had a ago.
* The config tool menu is so much more convenient to navigate thanks.
* OpenCV didn't seem any quicker but it may be because I didn't actually time it for comparison.
* I started off with unpaired controllers to fully test it. Pairing the PSMoves was a cinch but the DS4 didn't work (but there's no problem pairing that with the native tool).
* I started by checking the controllers' orientation and the DS4 kept crashing during the gyro test [DS4 gyro break.txt](https://github.com/cboulay/PSMoveService/files/410660/DS4.gyro.break.txt). This happens randomly but after only a few seconds. The error spews into the log and is only stopped by closing the config tool. I couldn't find where the log was getting saved to (another bug?) so I just copied it.
* All the models seemed fine in SteamVR now (the laser shoots out of the bottom of the DS4?).
* I have to get closer to my cameras to get the DS4 recognised. I don't think it's a bug, just something to note because the light bar is smaller and thin so it gets aliased with the low resolution.

I think that's everything.

Again here's a copy for any one else (the build size is much smaller now for some reason)
[PSMS-4cef4b1.7z.txt](https://github.com/cboulay/PSMoveService/files/410673/PSMS-4cef4b1.7z.txt)

**Comment by HipsterSloth** [comment]
@zelmon64 Thanks again for your comprehensive testing and write-up! It's much appreciated.

> I started off with unpaired controllers to fully test it. Pairing the PSMoves was a cinch but the DS4 didn't work (but there's no problem pairing that with the native tool).

Yeah the pairing for the DS4 is not great (and by not great I mean terrible). It worked for me BUT it required many attempts (retrying for a minute sometimes) to get it to take. Getting pairing in Windows seems to be a timing sensitive operation per device type. I'm currently using the same pairing timings as the PSMove. Which native pairing tool are you using? I should take a look at that and see what I can learn.

> I started by checking the controllers' orientation and the DS4 kept crashing during the gyro test

Whoops. Good catch. Looks like I'm putting too much data in the UDP controller packet when using that test tool. I need to either cut down what I'm sending or increase the UDP packet size (currently 500 bytes). I'll try and fix that today since that's likely a pretty easy tweak.

>  I couldn't find where the log was getting saved to (another bug?) so I just copied it.

I recently had to rip out my usage of boost logging (OS X build problem, see end of issue #35) and replace it with my own simpler implementation. My simpler implementation doesn't have logging to file yet. I actually want to completely redo how we handle logging. We current use iostream style logging (as compared to printf style logging). It's hard to make iostream style logging multi-threaded safe, so I would rather just redo it all as printf style logging. But that's a big undertaking and I wanted to get the other filtering stuff done first. Unfortunately that means people have to copy out of the log window for now, which is a bummer.

> (the laser shoots out of the bottom of the DS4?).

Hmm. I'm rotating the DS4 model 90 degrees in the [steamvr plugin](https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L1652-L1659) to get the controller model to line correctly with the orientation the service is providing. Maybe I should do that rotation somewhere else. I'll have to think about where the best place to do that rotation is (maybe in the source model?).

> I have to get closer to my cameras to get the DS4 recognised. I don't think it's a bug, just something to note because the light bar is smaller and thin so it gets aliased with the low resolution.

Yeah that 's definitely the issue with the DS4 and why Sony had to upgrade to the PS4 Camera to get a consumer friendly tracking range. I'm hoping a combination of a recenter button and better IMU filtering (with the Kalman filter) will help with that somewhat. Once the filter work is in a good place I'm going to look back into supporting higher resolution cameras. 

Do you know of any HD webcams that can update at 60hz btw? The Logitech C920 used to support that, but then they started hardware locking that feature. It seems like it's hard to find a reasonably priced HD camera that can update at 60hz.

**Comment by zelmon64** [comment]
> Yeah the pairing for the DS4 is not great (and by not great I mean terrible). It worked for me BUT it required many attempts (retrying for a minute sometimes) to get it to take. Getting pairing in Windows seems to be a timing sensitive operation per device type. I'm currently using the same pairing timings as the PSMove. Which native pairing tool are you using? I should take a look at that and see what I can learn.

I'm just using the basic Windows 10 Bluetooth settings connecting tool. I'm wondering if you're missing the part about putting the DS4 into pairing mode by holding the share button when you turn it on with the PS button. When I use that I can reliably reconnect it to different computers.

> Hmm. I'm rotating the DS4 model 90 degrees in the steamvr plugin to get the controller model to line correctly with the orientation the service is providing. Maybe I should do that rotation somewhere else. I'll have to think about where the best place to do that rotation is (maybe in the source model?).

Just to clarify, I would expect the laser to shoot out from the light bar but instead it's coming from whre the bar code is.

> Do you know of any HD webcams that can update at 60hz btw? The Logitech C920 used to support that, but then they started hardware locking that feature. It seems like it's hard to find a reasonably priced HD camera that can update at 60hz.

That's a bummer about the C920, that's my favourite webcam (and the only one I own apart from the PSEye). The only one I can think of is the Logitech Quickcam 9000 Pro Doc_Ok used in that tracking video but again I think it's limit is 30Hz. I'll keep an eye out.

> EDIT: I just tried running the "test orientation" on the DS4 controller but I couldn't repro the issue here at work. If you look in PSMoveControllerInterface.h is MAX_OUTPUT_DATA_FRAME_MESSAGE_SIZE set to 500 for you? Also have you run a clean build? I'll try a a fresh build at home and see if the issue repros there. Also if you change MAX_OUTPUT_DATA_FRAME_MESSAGE_SIZE to something larger (like 600?) does that fix it for you?

I did the same git instructions for a fresh build you gave me last time (minus the hacks) and followed the build from scratch wiki. The value in `PSMoveProtocolInterface.h ` was set to 500 so I changed it to 600 and rebuilt. The crashing did not happen again but no controller would remain lit. I then returned to 500 and the lights returned to normal but the crash did not reoccur (I don't know why).

**Comment by HipsterSloth** [comment]
Part 1 of the video explaining this changes is up: 

> I'm just using the basic Windows 10 Bluetooth settings connecting tool. I'm wondering if you're missing the part about putting the DS4 into pairing mode by holding the share button when you turn it on with the PS button. When I use that I can reliably reconnect it to different computers.

Oh! I have never tried holding the share button. I will try that next time.

> Turns out the DS4 gyro test is only crashing when only the DS4 is connected. 

Interesting. I'll give that test case a try tomorrow. Sounds like you setup up everything correctly on your end.

Also I have part 2 of the DS4 video up. 

[DS4TrackingPt2](https://youtu.be/MPbegaB7cf0 "DS4TrackingPt2")
 
@cboulay This video goes into the details of the current optical pose extraction for the ds4 and the IMU blending. I'd love any feedback you have on this, especially if anything sticks out about how to best proceed with making the DS4 UKF model.

**Comment by zelmon64** [comment]
@HipsterSloth I saw you said you are holding off the release because of the DS4 gyro crashing. Have you been able to recreate it? Should I run some more tests? I'd hate it if it's just my rig causing you to waste your time. Related to this, I'm curious if the DS4 pairing mode made any difference for you?

**Comment by HipsterSloth** [comment]
@zelmon64 I have not repro'd that crash yet, but I haven't really investigated too much. Haven't tried the pairing tests either. I was pretty much head down working on kalman filter stuff all thu/fri. I'd actually be curious if you get any gyro crash with just using the psmove. If not I might put out a release with the new code since it has a few new fixes in it. Until the Kalman filter work is done the ds4 isn't officially supported anyway (since the tracking is really usable yet).

**Comment by zelmon64** [comment]
@HipsterSloth That's very fair - I'm really looking forward to the Kalman filter!

I haven't had any gyro crashes with the psmoves. So far the DS4 only crashes during the guro test if it is detected as the first or second controller. It does not seem to crash if it is the third (yellow).

When I started this round of tests I had only one psmove connected and it had the Steam Controller model. What is interesting is that the laser was coming out where it should (the top instead of the back).  This model swap seems to only happen on the first run but I can't say for sure.

**Pull request merged**
